### ISSUE TITLE
Fonts stop working

### ISSUE THREAD

**Issue by kimchibreath** [FLPub/symbaroum5ecore#8] opened 2022-03-08 16:24 UTC
I don't like the module's character sheet background (it's very difficult to read and tbqh, I think it's not so nice looking, sorry), so I chose "DnD5E Default" in the module's settings under 'Character Background Images' because it's light, plain and the text is easy to read against it--once I do that, the character sheet stops using whatever fonts you've defined in the module stylesheet. I then swapped to the Default 5e Sheet in my character sheet and THOSE fonts work, but then I don't get the Symbaroum corruption row. I then swap back to the Symbaroum sheet and the fonts _still_ don't work. I've tried this in both Chrome and Firefox. It's like once I change the character background image to 'DND5e Default', the defined fonts from the stylesheet no longer work.

I have done this on both my computer via the web client, and on my husband's computer via the Foundry VTT app. We've been able to replicate it this issue on both of our computers. The only thing I can figure is that when you change the character sheet background to the DND5e Default, something gets written to the stylesheet or the html for the character sheet itself that prevents the text styles from applying.

![foundry vtt](https://user-images.githubusercontent.com/37221628/157278896-365729ff-e2b5-4734-a629-26ccd7284288.png)

**Comment by pwatson100** [comment] 2022-03-08 17:42
Thank you for your feedback.
In the next release there are new backgrounds that are a lot less "Busy".  
The idea of the "DnD5E Default" is that it reverts all of the settings back to the standard sheet settings so the normal colours and fonts.  We did this to enable people that don't like the backgrounds or the new font to be able to reset the Symbaroum sheet back to something they are more comfortable with.  
But in looking at this I did find a bug where the fonts were being set the same on the PC and NPC sheet which is not what was intended,  
If you want to keep the font but change the background to grey (or another colour) use the "Plain Color Picker" option to pick a background colour and the Text colour picker to choose a suitable font.

**Comment by kimchibreath** [comment] 2022-03-08 18:32
Well once it's changed, it won't go back. So, until you guys update it, the install is stuck with Times New Roman everywhere in the Symbaroum 5e character sheets; it's so weird too because some of the numbers are displayed with 'Modesto Condensed' and then the rest is just Times New Roman.

**Comment by trioderegion** [comment] 2022-03-08 18:35
I believe the font issue is a duplicate of #5, which will be rolled into today's update.

**Closed** 2022-03-08 18:55 UTC
