### ISSUE TITLE
Rest buttons are not operating as intended. 

### ISSUE THREAD

**Issue by Elrew** [FLPub/symbaroum5ecore#46] opened 2022-10-02 00:49 UTC
Version 10, build 286. Using RoS Core, Bestiary, GM Guide, and Players guide. All of them are version 1.0.1 but Core is 2.0.0. System is D&D Core 5e version 2.0.3

When clicking on the rest buttons they do not update the character sheet. Also, when doing a short or long rest, and you choose to roll a hit die, it will sometimes roll all of the hit die at once. This has happened to me just a few times. I was also using a module named Read Set Roll and that caused a conflict so I deactivated it. That may have been the root of the hit die issue.

**Comment by trioderegion** [comment] 2022-10-02 01:02
Marking as duplicate of #45 . Thank you very much for the confirmation!

**Closed** 2022-10-04 18:08 UTC
Labels: bug, duplicate
