### ISSUE TITLE
DnD5e Default settings option for PC and NPC sheets does not match the expected styling

### ISSUE THREAD

**Issue by dirusulixes** [FLPub/symbaroum5ecore#21] opened 2022-03-22 22:45 UTC
fvtt 9.255
symbaroum5ecore 1.0.1

I'm not sure if this is a misunderstanding of the setting intended behaviour from my part, but the option DnD5e default for PCs and NPCs sym5e sheets does not reproduce the default DnD5e sheet styling. Fonts and background are different. 

![image](https://user-images.githubusercontent.com/5693623/159587252-6ce5f74f-f922-4ff7-9249-6e7250989d1c.png)

**Comment by pwatson100** [comment] 2022-03-22 22:57
It's intended to reproduce the colours and fonts. If you want to switch to the dnd5e sheet you have to select the sheet gear on the sheet and change it there.

**Comment by dirusulixes** [comment] 2022-03-22 23:04
Just to clarify, what I'm reporting is that the sym5e sheet after selecting the setting `Default DND5e settings...` does not seem to reproduce the fonts of the dnd5e sheet.
![image](https://user-images.githubusercontent.com/5693623/159590548-1dbbade7-20df-4a8c-8f35-49b18bf79690.png)

**Comment by pwatson100** [comment] 2022-03-23 00:03
Ah. Sorry I misunderstood.  I will check into it.

**Comment by pwatson100** [comment] 2022-03-23 00:19
Yea.  I bug crawled in. It should be set to "Modesto Condensed".  I have fixed it now and it will be in the next release.

**Closed** 2022-03-23 00:20 UTC
